#!/bin/bash
#
# Script that commits any changes in a target directory, prior to running gmr processing
#  
# TARGETDIR     $1: target directory 
# GMRPROCESSING $2: Y if this commit is being done as part of GMR processing, 
#                   N if we are saving the state prior to starting GMR.  
# TAG           $3: tag to assign to the new commit.  
#  Tag convention:  yyyy.mm.dd for GMR; yyyy.mm.dd[Tx]-prior if before GMR  
# ===================================================================
umask 0002
echo "$0 starting..."
TARGETDIR="$1"
GMRPROCESSING="$2"
TAG="$3"
cd $TARGETDIR
git checkout master
git add -A
if [[ "$GMRPROCESSING" == "Y" ]]; then
  git commit -m "GMR processing for $TAG"
  COMMITRC="$?"
else
  git commit -m "commit with tag $TAG prior to GMR processing"
  COMMITRC="$?"
fi
if [[ "$COMMITRC" -eq 0 ]]; then
  git push origin master 
  git tag $TAG
  git push origin $TAG
  echo "committed latest changes to $TARGETDIR as $TAG"
else 
  echo "no changes to commit for $TARGETDIR"
fi
echo "$0 complete"
