#!/bin/bash
# ===================================================================
# Load target word caches 
# Some scripts may fail if this is not submitted on ambrosia
# $1:  LOGFILE to update with results
# $2:  STEP number of the overall gmrbuild job
# $3:  NOTIFYEMAIL: email address to notify
# $4:  TEMPMSG:  temp message file for email
# $5:  NOW: yyyy.mm.dd
# $6:  LOGDETAILFILE
# ===================================================================
echo "$0 starting..."
LOGFILE="$1"
STEP="$2"
NOTIFYEMAIL="$3"
TEMPMSG="$4"
NOW="$5"
LOGDETAILFILE="$6"
BASE=~/test
ERRORLOG=$BASE/twcache_error.log
function wordCache() {
  export TARGETDIR=$BASE 
  export SOURCEDIR=$BASE
  cd $TARGETDIR
  JSON_FILE=`head infiles.txt --lines=1`
  echo "loading target word cache for $1 using file $JSON_FILE"
  m4detect --cms-twcache-only -g -v -j $JSON_FILE >> $ERRORLOG  2>&1 
}
wordCache
WORDCACHES=`grep 'Caching retrieved target words' $ERRORLOG | wc -l`
OLDCACHES=`grep 'Loading cached target words' $ERRORLOG | wc -l`
NOWTIME=$(date +"%Y.%m.%d--%H-%M")
# time msg, $2 is step
if [[ "$WORDCACHES" -eq "$NUM" || "$OLDCACHES" -eq "$NUM" ]]; then
   echo "$NOWTIME STEP $STEP SUCCESS: $0" >> $LOGFILE
   exit 0
else
   echo "$NOWTIME STEP $STEP FAIL: $0. Expected $NUM target word caches (found $WORDCACHES new and $OLDCACHES existing.)" > $TEMPMSG
   cat $TEMPMSG >> $LOGFILE
   notify $NOTIFYEMAIL $TEMPMSG
   rm -f $TEMPMSG
   exit 1
fi   
echo "$0: complete."
